# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H0a0gmXHa8c5Xu_VS91xUX50Zj9SKPku
"""

#1-1
import pandas as pd
df = pd.read_csv('edu_bigdata_imp1.csv', encoding='big5', low_memory=False)

df_filtered = df[df['PseudoID'] == 39]

unique_values = df_filtered['dp001_review_sn'].unique()

print(len(unique_values))

#1-2
import pandas as pd

df = pd.read_csv('edu_bigdata_imp1.csv', encoding='big5', low_memory=False)

df_filtered = df['PseudoID'].unique()
print(len(df_filtered))

df_filtered = df[df['PseudoID'] == 39]
print(len(df_filtered))

df_filtered = df_filtered.dropna(subset=['dp001_question_sn'])
print(len(df_filtered))

unique_values = df_filtered['dp001_question_sn'].unique()

print(len(unique_values))

#2.1
import pandas as pd

df = pd.read_csv('../../edu_bigdata_imp1.csv', encoding='big5', low_memory=False)

df_filtered = df[df['PseudoID'] == 281]

df_filtered = df_filtered['dp001_indicator'].unique()
print(len(df_filtered))
print(df_filtered)

#2.2
import pandas as pd

df = pd.read_csv('../../edu_bigdata_imp1.csv', encoding='big5', low_memory=False)

df_filtered = df[df['PseudoID'] == 281]

df_filtered = df_filtered[df_filtered['dp001_prac_score_rate'] == 100]
#print(df_filtered)
print(len(df_filtered))

#3.1
import pandas as pd

df = pd.read_csv('../../edu_bigdata_imp1.csv', encoding='big5', low_memory=False)

df_filtered = df[df['PseudoID'] == 71]

df_filtered = df_filtered[df_filtered['dp001_record_plus_view_action'] == "paused"]
#print(df_filtered)
print(len(df_filtered))

#3.2
import pandas as pd

df = pd.read_csv('../../edu_bigdata_imp1.csv', encoding='big5', low_memory=False)

df_filtered = df[df['PseudoID'] == 71]

start_date = df_filtered['dp001_review_start_time']

end_date = df_filtered['dp001_review_end_time']

start_date.add(end_date)

date = pd.to_datetime(start_date).dt.date.drop_duplicates()

print(date)

#4.1
import pandas as pd

df = pd.read_csv('../../edu_bigdata_imp1.csv', encoding='big5', low_memory=False)

df_sn = df['dp001_review_sn'].value_counts()

print(int(df_sn.idxmax()))

#4.2
import pandas as pd

df = pd.read_csv('edu_bigdata_imp1.csv', encoding='big5', low_memory=False)

df_filtered = df['dp002_extensions_alignment'].dropna()

bools = df_filtered.str.contains('十二年國民基本教育類')

value = df_filtered[bools].count()

print(value)
#4.3
import pandas as pd

df = pd.read_csv("/content/edu_bigdata_imp1.csv", encoding = "big5", low_memory = False)

print(df["dp002_verb_display_zh_TW"].dropna().value_counts().head(3))

#4.4
import pandas as pd

df = pd.read_csv("/content/edu_bigdata_imp1.csv", encoding = "big5", low_memory = False)

extensions = df["dp002_extensions_alignment"].dropna()

bools = extensions.str.contains('校園職業安全')
print(extensions[bools].count())